# Generated by Django 4.2 on 2024-04-17 15:40

import django.contrib.gis.geos.point
from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(default='', max_length=255)),
                ('location', location_field.models.plain.PlainLocationField(default=django.contrib.gis.geos.point.Point(51.389, 35.6892), max_length=63)),
            ],
        ),
    ]
